
{{- $name := "order-service" -}}
{{- $image := .Values.orderService.image -}}
{{- $replicas := .Values.orderService.replicas -}}
{{- $port := .Values.orderService.servicePort -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ $image }}
          imagePullPolicy: Never          
          ports:
            - containerPort: {{ $port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - port: {{ $port }}
      targetPort: {{ $port }}
